### ISSUE TITLE
Crash on startup from DevCreateNewForm

### ISSUE THREAD

**Issue by Nytra** [ResoniteModdingGroup/MonkeyLoader.GamePacks.ResoniteModLoader#1]
Try loading [Component Search Wizard](https://github.com/Nytra/ResoniteComponentSearchWizard)

```
System.TypeInitializationException: The type initializer for 'FrooxEngine.DevCreateNewForm' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object
```

[DeselectOwnGizmos](https://github.com/badhaloninja/DeselectOwnGizmos) also gives a similar error.

Log file:

[DESKTOP-H976HO2 - 2024.4.26.1258 - 2024-04-28 21_44_17.log](https://github.com/ResoniteModdingGroup/MonkeyLoader.GamePacks.ResoniteModLoader/files/15143664/DESKTOP-H976HO2.-.2024.4.26.1258.-.2024-04-28.21_44_17.log)

**Comment by Banane9** [comment]
That's curious, as the Component Search Wizard worked fine for me 🤔

**Comment by Banane9** [comment]
Can you try without DeselectOwnGizmos?

**Comment by Nytra** [comment]
It works without DeselectOwnGizmos

**Comment by Banane9** [comment]
mmmm, right, I think I figured it out. I didn't pay attention while postfixing `EngineInitializer.InitializeFrooxEngine`. It returns a Task, so postfixing the method makes it actually run *before* the code in the method has run. Which just so happens to also include initializing the component library which `DevCreateNew`'s static constructor accesses.

As far as I can tell, initializing the component library happens concurrent with RML being invoked anyways, so that this ever consistently worked is somewhat surprising. Although there is [this issue](https://github.com/badhaloninja/DeselectOwnGizmos/issues/2), I guess - from before I made this integration.
