### ISSUE TITLE
Add info for how to build from source

### ISSUE THREAD

**Issue by Nytra** [ResoniteModdingGroup/MonkeyLoader.GamePacks.ResoniteModLoader#5]
I can't build this because it can't find nuget packages, but I don't know how to add those

```
error NU1101: Unable to find package Resonite.Elements.Core. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org

error NU1101: Unable to find package MonkeyLoader. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org

error NU1101: Unable to find package MonkeyLoader.GamePacks.Resonite. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org

error NU1101: Unable to find package Resonite.FrooxEngine. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
```

**Comment by Nytra** [comment]
It is also asking me for a username and password for `pkg.munally.com`

**Comment by Banane9** [comment]
> It is also asking me for a username and password for `pkg.munally.com`

Hmmmm... blame @ljoonal on that one. git.ljoonal.xyz seems to be down too :'D

**Comment by l-2-j** [comment]
> It is also asking me for a username and password for pkg.munally.com

Was down for like an hour whilst I was editing the nginx config to try to proxy my own git server as well, ended up just mostly reverting the changes after an hour. I didn't think anyone relied on too much, due to https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/456 making it so that in addition to just the publicly available packages, you need to _also_ add some private ones... Which I thought most people would probably do on GitHub with https://github.com/MonkeyModdingTroop/ReferencePackageGenerator
